name: buddyappfirebase
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.16.0
    # http request
  http: ^0.12.0+2
    # async package to add additional Cancellable operations
  async: ^2.0.8
    # get it
  get_it: ^3.0.0+1
    # provider
  provider: ^3.2.0
    # provider architecture
  provider_architecture: ^1.0.3
    # Button Designs

  modal_progress_hud: ^0.1.3

  firebase_messaging: ^6.0.13

  cloud_firestore: ^0.12.9+5

  shared_preferences: ^0.5.3+4

  font_awesome: ^5.10.1

  intl: ^0.15.7

  autocomplete_textfield: ^1.7.3

  link: ^1.0.0

  simple_animations: ^1.3.3

  google_fonts: ^1.1.0

  cupertino_icons: ^0.1.3

  random_string: ^2.0.1

  curved_navigation_bar: ^0.3.4

  



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/like.jpg
    - assets/images/love.jpg
    - assets/images/haha.png
    - assets/images/wow.jpg
    - assets/images/sad.png
    - assets/images/img_not_available.jpeg
    - assets/images/explore.jpg
    - assets/images/connect.jpg
    - assets/images/setup.jpg
    - assets/images/img.png
    - assets/images/chem.jpeg
    - assets/images/card_dog_1.png
    - assets/images/chemistry.jpg
    - assets/images/coding.jpg
    - assets/images/history.jpg
    - assets/images/english.jpg
    - assets/images/literature.jpg
    - assets/images/psychology.jpg
    - assets/images/history1.jpg
    - assets/images/psychology1.jpg
    - assets/images/chemistry1.jpg